- name: Include tasks for ingest
  include_tasks: name = ingest.yml
  when: logstash_config == "ingest"

- name: Include tasks for digest
  include_tasks: name = digest.yml
  when: logstash_config == "digest"

- name: copy pipeline configuration
  template:
    src: "logstash-{{ logstash_config }}.conf.j2"
    dest: "{{ logstash_pipeline_dir }}/logstash-{{logstash_config}}.conf"
    mode: 0644
  register: result

- name: restart logstash
  service: 
    name: logstash
    state: restarted
  when: result is changed or keys is changed



