- name: Include tasks for ingest
  include_tasks: "{{ playbook_dir }}/roles/logstash/tasks/ingest.yml"
  when: logstash_config == "ingest"

- name: copy pipeline configuration for {{logstash_config}}
  template:
    src: "logstash-{{ logstash_config }}.conf.j2"
    dest: "{{ logstash_pipeline_dir }}/logstash-{{logstash_config}}.conf"
    mode: 0644
  register: result

- name: restart logstash
  service: 
    name: logstash
    state: restarted
  when: result is changed or keys is changed



