---
- hosts: elasticsearch
  remote_user: root
  roles:
  - { role: elasticsearch }

- hosts: zookeeper
  remote_user: root
  roles:
  - { role: zookeeper }

- hosts: kafka
  remote_user: root
  roles:
  - { role: kafka, tags: ["kafka"] }

- hosts: kibana
  remote_user: root
  roles:
  - { role: kibana }

- hosts: logstash-ingest
  remote_user: root
  roles:
  - { role: logstash, logstash_config: ingest  }

- hosts: logstash-digest
  remote_user: root
  roles:
  - { role: logstash, logstash_config: digest  }

- hosts: influxdb
  remote_user: root
  roles:
  - { role: influxdb, tags: ["influxdb"] }

- hosts: chronograf
  remote_user: root
  roles:
  - { role: chronograf, tags: ["chronograf"] }

- hosts: nginx
  remote_user: root
  roles:
  - { role: nginx, tags: ["nginx"] }


