- name: ensure /var/log/kafka dir exists
  file: path=/var/log/kafka state=directory

- name: copy kafka server configuration
  template: src=server.j2 dest=/root/{{kafka_pkg}}/config/server.properties
 
- name: Copy kafka systemd config
  template: src=kafka.service.j2 dest=/etc/systemd/system/kafka.service
  
- name: start kafka
  systemd:
    name: kafka
    daemon-reload: yes
    enabled: yes
    state: restarted
  
