- name: Add Elasticsearch repo
  template: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch-6.x.repo

- name: Install Kibana.
  yum: name=kibana-{{kibana_version}} state=present
  notify: restart kibana

- name: Copy Kibana configuration.
  template:
    src: kibana.yml.j2
    dest: "/etc/kibana/kibana.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: started
    enabled: yes


