#!/bin/sh
#
# chkconfig: 2345 22 79
# descrption: Kafka service
#

### BEGIN INIT INFO
# Required-Start: zookeeper
### END INIT INFO

SERVICE_NAME=kafka
SERVICE_CMD="/root/{{ kafka_pkg }}/bin/kafka-server-start.sh /root/{{ kafka_pkg }}/config/server.properties"
SERVICE_OUT=/var/log/kafka/kafka-output
PID=$(ps aux | grep kafka.*server.properties | grep -v grep | awk '{print $2}')

case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ -z $PID ]; then
            nohup $SERVICE_CMD 2>>1 >>$SERVICE_OUT &
            echo "$SERVICE_NAME started ..."
       else
            echo "$SERVICE_NAME is already running ..."
       fi
    ;;
    stop)
        if [ ! -z $PID ]; then
            echo "$SERVICE_NAME stoping ..."
            kill $PID
            echo "$SERVICE_NAME stopped ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ ! -z $PID ]; then
            echo "$SERVICE_NAME stopping ...";
            kill $PID
            echo "$SERVICE_NAME stopped ...";
        fi
        echo "$SERVICE_NAME starting ..."
        nohup $SERVICE_CMD 2>>1 >>$SERVICE_OUT &
        echo "$SERVICE_NAME started ..."
    ;;
    status)
        if [ ! -z $PID ]; then
            echo "$SERVICE_NAME is running (PID $PID)"
            exit 0
        else
            echo "$SERVICE_NAME is not running"
            exit 3
        fi
    ;;
esac 
