
- name: Install common dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - python-httplib2
    - net-tools
    - openssh
    
- name: disabled selinux
  selinux: state=disabled
  
- name: get SElinux mode
  command: /usr/sbin/getenforce
  register: enforce
  
- name: ensure SELinux is turned off
  command: /usr/sbin/setenforce 0
  when: enforce.stdout == 'Enforcing'
  
- name: ensure setup dir exists
  file: path='{{setupdir}}' state=directory

- name: ensure data dir exists
  file: path='{{datadir}}' state=directory

- name: Limits conf
  template: src=limits.conf.j2 dest=/etc/security/limits.conf

- name: Set timezone to UTC
  command: "timedatectl set-timezone Etc/UTC"

