---
# Configure Elasticsearch Node

#Create required directories
- name: Create Directories
  file: path={{ item }} state=directory owner={{ es_user }} group={{ es_group }}
  with_items:
    - "{{pid_dir}}"
    - "{{log_dir}}"
    - "{{conf_dir}}"
    - "{{data_dirs}}"

#Copy the config template
- name: Copy Configuration File
  template: src=elasticsearch.yml.j2 dest={{conf_dir}}/elasticsearch.yml owner={{ es_user }} group={{ es_group }} mode=0644 force=yes
  register: system_change
  notify: restart elasticsearch

#Copy the systemd specific file if systemd is installed
- name: Copy Systemd File for Instance
  template: src=elasticsearch.systemd.j2 dest={{sysd_script}} mode=0644 force=yes
  notify:
  - reload systemd configuration
  - restart elasticsearch

#Copy the instance specific default file
- name: Copy Default File for Instance
  template: src=elasticsearch.j2 dest={{default_file}} mode=0644 force=yes
  notify: restart elasticsearch


- name: Copy jvm.options File for Instance
  template: src=jvm.options.j2 dest={{conf_dir}}/jvm.options owner={{ es_user }} group={{ es_group }} mode=0644 force=yes
  notify: restart elasticsearch