---
- file: path=/etc/elasticsearch/templates state=directory owner={{ es_user }} group={{ es_group }}

- name: Copy templates to elasticsearch
  copy: src={{ item }} dest=/etc/elasticsearch/templates owner={{ es_user }} group={{ es_group }}
  with_fileglob:
    - "{{ es_templates_fileglob | default('') }}"

- name: Ensure elasticsearch is started
  service: name=elasticsearch state=started enabled=yes

- name: Wait for elasticsearch to startup
  wait_for: host={{es_api_host}} port={{es_api_port}} delay=10
  when: es_start_service

- name: Install templates without auth
  uri:
    url: "http://{{es_api_host}}:{{es_api_port}}/_template/{{item | filename}}"
    method: PUT
    status_code: 200
    body_format: json
    body: "{{ lookup('file', item) }}"
  with_fileglob:
    - "{{ es_templates_fileglob | default('') }}"
  run_once: True

