---
- name: check-set-parameters
  include: elasticsearch-parameters.yml
  tags:
      - always

- include: elasticsearch.yml
  tags:
      - install

- include: elasticsearch-config.yml
  tags:
      - config

- meta: flush_handlers

#Templates done after restart - handled by flushing the handlers. e.g. suppose user removes security on a running node and doesn't specify es_api_basic_auth_username and es_api_basic_auth_password.  The templates will subsequently not be removed if we don't wait for the node to restart.
- include: elasticsearch-template.yml
  when: es_templates
  tags:
      - templates

- name: Make sure elasticsearch is started
  service: name=elasticsearch state=started enabled=yes
  when: es_start_service

- name: Wait for elasticsearch to startup
  wait_for: host={{es_api_host}} port={{es_api_port}} delay=5 connect_timeout=1
  when: es_restarted is defined and es_restarted.changed and es_start_service


